# Static Visualizations

## Importing data, packages

In [4]:
# importing packages
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [13]:
df = pd.read_csv('SD_CANTAB_DB_public.csv')
df

,Subject ID,DMS Recommended Standard Status,MOT Voice Status,PAL Recommended Standard Status,RTI Five-Choice Status,RVP 3 Targets Status,SWM Recommended standard 2.0 Status,DMSCC,DMSL0SD,DMSL12SD,...,SWMTE4,SWMTE6,SWMTE8,SWMWE,SWMWE4,SWMWE6,SWMWE8,Unnamed: 108,Notes,Unnamed: 110
0,SUBJ001_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,647.7034,1082.0378,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,SUBJ002_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,254.2214,1088.2416,...,0.0,0.0,6.0,2.0,0.0,0.0,2.0,NaN,NaN,NaN
2,SUBJ003_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,412.0081,1584.2954,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,SUBJ004_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,NOT_RUN,COMPLETED,1.10,515.5343,294.7749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,RVP didn't run,NaN
4,SUBJ005_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,476.0976,1081.0911,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
5,SUBJ006_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,1035.2339,690.0784,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
6,SUBJ007_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.15,1034.7602,1643.3607,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
7,SUBJ008_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,600.6405,633.4787,...,0.0,3.0,7.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
8,SUBJ009_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,1333.2896,1124.6276,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
9,SUBJ010_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,1670.3226,852.5372,...,0.0,0.0,8.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,SUBJ001_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,1515.0139,1769.4325,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
12,SUBJ002_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.15,542.2973,457.9755,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
13,SUBJ003_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.10,526.3297,1449.0232,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
14,SUBJ004_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.25,1430.3905,846.4068,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
15,SUBJ005_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.10,1133.7279,4045.6971,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
16,SUBJ006_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,260.3517,796.9063,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
17,SUBJ007_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.15,252.5595,1354.0492,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
18,SUBJ008_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,820.8772,503.5444,...,0.0,2.0,17.0,7.0,0.0,0.0,7.0,NaN,NaN,NaN
19,SUBJ009_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.25,1401.6110,596.5177,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
20,SUBJ010_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,726.5086,337.1517,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [9]:
sleep = df.iloc[:10]
sleep

,Subject ID,DMS Recommended Standard Status,MOT Voice Status,PAL Recommended Standard Status,RTI Five-Choice Status,RVP 3 Targets Status,SWM Recommended standard 2.0 Status,DMSCC,DMSL0SD,DMSL12SD,...,SWMTE4,SWMTE6,SWMTE8,SWMWE,SWMWE4,SWMWE6,SWMWE8,Unnamed: 108,Notes,Unnamed: 110
0,SUBJ001_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,647.7034,1082.0378,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,SUBJ002_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,254.2214,1088.2416,...,0.0,0.0,6.0,2.0,0.0,0.0,2.0,NaN,NaN,NaN
2,SUBJ003_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,412.0081,1584.2954,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,SUBJ004_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,NOT_RUN,COMPLETED,1.10,515.5343,294.7749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,RVP didn't run,NaN
4,SUBJ005_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,476.0976,1081.0911,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
5,SUBJ006_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,1035.2339,690.0784,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
6,SUBJ007_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.15,1034.7602,1643.3607,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
7,SUBJ008_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,600.6405,633.4787,...,0.0,3.0,7.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
8,SUBJ009_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,1333.2896,1124.6276,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
9,SUBJ010_before,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,1670.3226,852.5372,...,0.0,0.0,8.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN

In [10]:
no_sleep = df.iloc[11:]
no_sleep

,Subject ID,DMS Recommended Standard Status,MOT Voice Status,PAL Recommended Standard Status,RTI Five-Choice Status,RVP 3 Targets Status,SWM Recommended standard 2.0 Status,DMSCC,DMSL0SD,DMSL12SD,...,SWMTE4,SWMTE6,SWMTE8,SWMWE,SWMWE4,SWMWE6,SWMWE8,Unnamed: 108,Notes,Unnamed: 110
11,SUBJ001_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,1515.0139,1769.4325,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
12,SUBJ002_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.15,542.2973,457.9755,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
13,SUBJ003_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.10,526.3297,1449.0232,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
14,SUBJ004_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.25,1430.3905,846.4068,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
15,SUBJ005_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.10,1133.7279,4045.6971,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
16,SUBJ006_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.05,260.3517,796.9063,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
17,SUBJ007_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.15,252.5595,1354.0492,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
18,SUBJ008_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,820.8772,503.5444,...,0.0,2.0,17.0,7.0,0.0,0.0,7.0,NaN,NaN,NaN
19,SUBJ009_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.25,1401.6110,596.5177,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
20,SUBJ010_after,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,1.00,726.5086,337.1517,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [14]:
for c in df.columns:
    print(c)

Subject ID
DMS Recommended Standard Status
MOT Voice Status
PAL Recommended Standard Status
RTI Five-Choice Status
RVP 3 Targets Status
SWM Recommended standard 2.0 Status
DMSCC
DMSL0SD
DMSL12SD
DMSL4SD
DMSLADSD
DMSLSD
DMSLSSD
DMSMDL
DMSMDL0
DMSMDL12
DMSMDL4
DMSMDLAD
DMSMDLS
DMSML
DMSML0
DMSML12
DMSML4
DMSMLAD
DMSMLS
DMSPC
DMSPC0
DMSPC12
DMSPC4
DMSPCAD
DMSPCS
DMSPEGC
DMSPEGE
DMSTC
DMSTC0
DMSTC12
DMSTC4
DMSTCAD
DMSTCS
DMSTE
DMSTEAD
DMSTEC
DMSTECAD
DMSTED
DMSTEDAD
DMSTEP
DMSTEPAD
MOTML
MOTSDL
MOTTC
MOTTE
PALFAMS
PALMETS
PALNPR
PALTA
PALTA2
PALTA4
PALTA6
PALTA8
PALTE
PALTE2
PALTE4
PALTE6
PALTE8
PALTEA
PALTEA2
PALTEA4
PALTEA6
PALTEA8
RTIFESI
RTIFESNR
RTIFESPR
RTIFMDMT
RTIFMDRT
RTIFMMT
RTIFMRT
RTIFMTSD
RTIFRTSD
RTIFTES
RVPA
RVPLSD
RVPMDL
RVPML
RVPPFA
RVPPH
RVPTFA
RVPTH
RVPTM
SWMBE
SWMBE4
SWMBE6
SWMBE8
SWMDE
SWMDE4
SWMDE6
SWMDE8
SWMPR
SWMS
SWMS6
SWMTE
SWMTE4
SWMTE6
SWMTE8
SWMWE
SWMWE4
SWMWE6
SWMWE8
Unnamed: 108
Notes
Unnamed: 110

In [15]:
reaction = df[["RTIFESI", "RTIFESNR", "RTIFESPR", "RTIFMDMT", "RTIFMDRT", "RTIFMMT", "RTIFMRT", "RTIFMTSD", "RTIFRTSD", "RTIFTES"]]
reaction

,RTIFESI,RTIFESNR,RTIFESPR,RTIFMDMT,RTIFMDRT,RTIFMMT,RTIFMRT,RTIFMTSD,RTIFRTSD,RTIFTES
0,0.0,0.0,0.0,257.0,320.5,258.9667,326.4000,30.6240,26.5390,0.0
1,0.0,0.0,0.0,227.5,330.5,227.0667,331.2000,25.9760,24.4221,0.0
2,0.0,0.0,0.0,254.0,337.5,259.5333,354.8667,47.0053,60.8416,0.0
3,0.0,0.0,0.0,278.0,322.0,277.6333,337.3000,43.5332,46.7607,0.0
4,0.0,0.0,0.0,211.0,346.5,215.8000,360.0000,28.1589,43.5280,0.0
5,1.0,0.0,0.0,244.0,309.0,247.1034,320.4828,37.1689,44.7163,1.0
6,0.0,0.0,1.0,221.0,308.0,223.3793,313.5862,35.1704,37.9384,1.0
7,0.0,0.0,1.0,219.0,395.0,225.3793,389.7931,31.1923,34.7967,1.0
8,0.0,0.0,0.0,295.5,317.0,297.7333,330.0333,31.5343,39.0804,0.0
9,0.0,0.0,0.0,236.0,351.0,240.2000,348.3333,25.0742,19.1983,0.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.0,0.0,0.0,294.0,329.5,297.2000,338.3333,28.1920,29.6931,0.0
12,0.0,0.0,0.0,215.5,309.0,220.3000,308.6667,25.6033,22.4182,0.0
13,0.0,0.0,0.0,236.0,371.0,254.9310,391.4483,40.9773,72.8431,1.0
14,0.0,0.0,0.0,407.0,401.5,406.7333,419.2667,71.8197,87.9631,0.0
15,0.0,0.0,0.0,268.5,475.5,275.9000,499.4000,41.3658,129.7365,0.0
16,1.0,0.0,0.0,252.0,326.0,252.5862,336.7931,49.5108,40.9995,1.0
17,0.0,0.0,0.0,344.0,354.5,353.3000,363.3667,65.4418,45.2003,0.0
18,1.0,0.0,1.0,228.0,404.0,236.2500,410.0357,27.6132,47.7140,2.0
19,0.0,0.0,0.0,351.5,368.5,355.7667,378.9000,95.2111,66.6097,0.0
20,1.0,0.0,0.0,270.0,334.0,265.6552,338.4138,38.1822,38.9244,1.0

In [ ]:
import os
import pandas as pd
import numpy as np

data_dir = "wavelength/"

# Step 2: Get all .txt files in that folder
txt_files = [f for f in os.listdir(data_dir) if f.endswith(".txt")]

# Step 3: Dictionary to hold DataFrames per file
dataframes = {}

# Step 4: Read each wl1 and wl2 text file
for filename in txt_files:
    full_path = os.path.join(data_dir, filename)
    base_name = filename.split("_")[0]  # grabs just '001'
    suffix = "wl1" if "wl1" in filename else "wl2"

    # Parse all whitespace-separated numbers into float array
    with open(full_path, 'r') as file:
        values = [float(x) for x in file.read().split()]
    
    rows = len(values) // 120
    reshaped = np.array(values[:rows * 120]).reshape(rows, 120)
    
    df = pd.DataFrame(reshaped, columns=[f"{suffix}_ch{i+1}" for i in range(120)])
    dataframes[f"{base_name}_{suffix}"] = df

# Step 5: Combine wl1 and wl2 for each subject
combined_data = {}
for subject_id in set(k.replace("_wl1", "").replace("_wl2", "") for k in dataframes.keys()):
    if f"{subject_id}_wl1" in dataframes and f"{subject_id}_wl2" in dataframes:
        combined_df = pd.concat([dataframes[f"{subject_id}_wl1"], dataframes[f"{subject_id}_wl2"]], axis=1)
        combined_data[subject_id] = combined_df

# Step 6: Preview the combined dataframe for subject 001
combined_data["001"].head()

,wl1_ch1,wl1_ch2,wl1_ch3,wl1_ch4,wl1_ch5,wl1_ch6,wl1_ch7,wl1_ch8,wl1_ch9,wl1_ch10,...,wl2_ch111,wl2_ch112,wl2_ch113,wl2_ch114,wl2_ch115,wl2_ch116,wl2_ch117,wl2_ch118,wl2_ch119,wl2_ch120
0,0.569291,0.164906,0.068384,0.008305,0.004889,0.024453,0.012480,0.004140,0.004300,0.010010,...,0.004776,0.006529,0.007769,0.007201,0.005089,0.024028,0.015134,0.692875,0.164192,0.184921
1,0.012956,0.008975,0.005627,0.004293,0.003615,0.013916,0.007560,0.010080,0.003605,0.002763,...,0.009469,0.007735,0.003330,0.004540,0.011672,0.014880,1.193818,1.362491,0.941410,1.258750
2,0.375152,0.013410,0.009475,0.007308,0.013626,0.009340,0.009139,0.014734,0.002912,0.010169,...,0.015238,0.000844,0.006711,0.001627,0.005475,0.039724,1.293710,0.050105,0.905509,1.085725
3,0.010602,0.606684,0.010371,0.002073,0.018954,0.017283,0.016194,0.006857,0.006873,0.010317,...,0.011170,0.006614,0.012336,0.004305,0.011872,0.007106,1.240428,0.004745,0.924807,0.002478
4,0.006642,0.003909,0.003219,0.006550,0.007295,0.017761,0.014041,0.014474,0.016824,0.007269,...,0.010458,0.013425,0.007813,0.010616,0.014594,1.342344,0.262647,0.298719,0.812363,1.233561

In [5]:
combined_data["001"].head()

,wl1_ch1,wl1_ch2,wl1_ch3,wl1_ch4,wl1_ch5,wl1_ch6,wl1_ch7,wl1_ch8,wl1_ch9,wl1_ch10,...,wl2_ch111,wl2_ch112,wl2_ch113,wl2_ch114,wl2_ch115,wl2_ch116,wl2_ch117,wl2_ch118,wl2_ch119,wl2_ch120
0,0.527697,0.329149,0.132640,0.003905,0.009382,0.008292,0.011974,0.010132,0.005203,0.013700,...,0.008101,0.001964,0.004292,0.009526,0.052115,0.018654,0.194233,0.349551,0.279559,0.108757
1,0.009646,0.014036,0.005962,0.011309,0.004191,0.012585,0.005267,0.003014,0.016230,0.005511,...,0.008801,0.012588,0.013949,0.014164,0.011326,0.025072,0.139659,0.208841,0.357094,0.206448
2,0.360542,0.010333,0.003131,0.006922,0.013834,0.006147,0.003175,0.007402,0.009643,0.017604,...,0.009609,0.011163,0.001175,0.013746,0.004904,0.006436,0.299034,0.107521,0.885037,0.219052
3,0.008477,0.416949,0.014526,0.018061,0.016869,0.006457,0.003689,0.013840,0.004844,0.013484,...,0.015030,0.010395,0.005099,0.009232,0.005463,0.011928,0.894147,0.015104,0.742827,0.007583
4,0.015292,0.007454,0.005392,0.011606,0.014944,0.014241,0.004244,0.013810,0.004963,0.012133,...,0.006191,0.008606,0.002634,0.018246,0.015966,0.672452,0.293712,0.925371,0.148391,1.092966